# Generated by Django 4.0.1 on 2022-01-18 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='None', max_length='50')),
                ('created_by', models.TextField(default='None')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 1, 18, 17, 46, 2, 265826, tzinfo=utc))),
                ('rank', models.IntegerField(default='0')),
                ('preview', models.TextField(default='None')),
                ('text', models.TextField(default='None')),
                ('category', models.CharField(default='None', max_length=255)),
            ],
        ),
    ]
