# Generated by Django 4.0.1 on 2022-01-18 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(default='None', max_length=255)),
                ('text', models.TextField(default='None')),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 17, 56, 41, 224874, tzinfo=utc)),
        ),
    ]
