# Generated by Django 4.0.1 on 2022-01-23 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0003_feedback_date_alter_articles_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='name',
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='downloads'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.TextField(default='NULL', max_length='50'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created_by',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articles',
            name='preview',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(default='NULL'),
        ),
    ]
