# Generated by Django 4.0.1 on 2022-01-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0004_user_remove_articles_name_articles_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='photo_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='downloads'),
        ),
    ]
