# Generated by Django 4.0.1 on 2022-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0006_remove_articles_photo_name_articles_photo_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='photo_root',
        ),
        migrations.AddField(
            model_name='articles',
            name='photo_name',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
