# Generated by Django 4.0.1 on 2022-01-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0008_alter_articles_photo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='photo_name',
        ),
    ]
