# Generated by Django 4.0.1 on 2022-01-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0009_remove_articles_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_name',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='preview',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
