# Generated by Django 4.0.1 on 2022-01-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0010_articles_image_name_alter_articles_preview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image_name',
        ),
    ]
