# Generated by Django 4.0.1 on 2022-01-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0012_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='article_id',
            new_name='article',
        ),
    ]
