# Generated by Django 4.0.1 on 2022-01-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0013_rename_article_id_likes_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bananaAPP.articles'),
        ),
    ]
