# Generated by Django 4.0.1 on 2022-01-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0014_alter_likes_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
