# Generated by Django 4.0.1 on 2022-02-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananaAPP', '0018_delete_user_remove_articles_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='likes',
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='downloads', verbose_name='Image preview'),
        ),
    ]
